CREATE TABLE Books (
  BookId INT NOT NULL PRIMARY KEY IDENTITY(1, 1),
  Title VARCHAR(255) NOT NULL,
  Description VARCHAR(MAX) NULL,
  CoverImage VARCHAR(MAX) NULL
);

CREATE TABLE Categories (
  CategoryId INT NOT NULL PRIMARY KEY IDENTITY(1, 1),
  Name VARCHAR(32) NOT NULL
);

CREATE TABLE BookCategories (
  BookId INT NOT NULL FOREIGN KEY REFERENCES Books(BookId),
  CategoryId INT NOT NULL FOREIGN KEY REFERENCES Categories(CategoryId),
);

CREATE TABLE Users (
  UserId INT NOT NULL PRIMARY KEY IDENTITY(1, 1),
  Username VARCHAR(64) NOT NULL,
  Name VARCHAR(256) NOT NULL,
  Surname VARCHAR(256) NOT NULL,
  PasswordHash VARCHAR(512) NOT NULL,
  Phone VARCHAR(15) NULL,
  IsAdmin BIT NOT NULL
);

CREATE TABLE Loans (
  BookId INT NOT NULL FOREIGN KEY REFERENCES Books(BookId),
  UserId INT NOT NULL FOREIGN KEY REFERENCES Users(UserId),
  StartDate DATE NOT NULL,
  EndDate DATE NULL
);

CREATE TABLE Reviews (
  ReviewId INT NOT NULL PRIMARY KEY IDENTITY(1, 1),
  Title VARCHAR(255) NOT NULL,
  Description VARCHAR(MAX) NOT NULL,
  Score INT NOT NULL,
  BookId INT NOT NULL FOREIGN KEY REFERENCES Books(BookId),
  UserId INT NOT NULL FOREIGN KEY REFERENCES Users(UserId)
);
