CREATE TABLE Books (
  BookId INT NOT NULL PRIMARY KEY IDENTITY(1, 1),
  Title VARCHAR(255) NOT NULL,
  Description VARCHAR(MAX) NULL,
  CoverImage VARCHAR(MAX) NULL
);

CREATE TABLE Users (
  UserId INT NOT NULL PRIMARY KEY IDENTITY(1, 1),
  Username VARCHAR(64) NOT NULL,
  Name VARCHAR(256) NOT NULL,
  Surname VARCHAR(256) NOT NULL,
  Phone VARCHAR(15) NULL,
);

CREATE TABLE Loans (
  BookId INT NOT NULL FOREIGN KEY REFERENCES Books(BookId),
  UserId INT NOT NULL FOREIGN KEY REFERENCES Users(UserId),
  StartDate DATE NOT NULL,
  EndDate DATE NULL
);
